// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNN24VR7qty1Ew19QR5SGS9zBmyq5KZaw',
    appId: '1:620778595301:web:7cf2aeb00b6852c99e050c',
    messagingSenderId: '620778595301',
    projectId: 'device-streaming-2128d6e7',
    authDomain: 'device-streaming-2128d6e7.firebaseapp.com',
    storageBucket: 'device-streaming-2128d6e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBkIyWwHiuYWuLpUpF8AP2mNNbH6dE8rI',
    appId: '1:620778595301:android:8657c840bac434c29e050c',
    messagingSenderId: '620778595301',
    projectId: 'device-streaming-2128d6e7',
    storageBucket: 'device-streaming-2128d6e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmhE3TiQ9Gluz5wjJKSJLDA9GVQh7STA0',
    appId: '1:620778595301:ios:02c55e3eedf982d09e050c',
    messagingSenderId: '620778595301',
    projectId: 'device-streaming-2128d6e7',
    storageBucket: 'device-streaming-2128d6e7.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmhE3TiQ9Gluz5wjJKSJLDA9GVQh7STA0',
    appId: '1:620778595301:ios:02c55e3eedf982d09e050c',
    messagingSenderId: '620778595301',
    projectId: 'device-streaming-2128d6e7',
    storageBucket: 'device-streaming-2128d6e7.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNN24VR7qty1Ew19QR5SGS9zBmyq5KZaw',
    appId: '1:620778595301:web:9a6d469ee35ef1ff9e050c',
    messagingSenderId: '620778595301',
    projectId: 'device-streaming-2128d6e7',
    authDomain: 'device-streaming-2128d6e7.firebaseapp.com',
    storageBucket: 'device-streaming-2128d6e7.firebasestorage.app',
  );
}
